In [2]:
import torch 

In [2]:
x=torch.tensor(3.0,requires_grad=True)

In [3]:
y=x**2

In [4]:
z=torch.sin(y)

In [5]:
x

tensor(3., requires_grad=True)

In [6]:
y

tensor(9., grad_fn=<PowBackward0>)

In [7]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [8]:
z.backward()

In [10]:
x.grad

tensor(-5.4668)

## Sigmoid activation 

In [4]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)

In [5]:
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [6]:
w

tensor(1., requires_grad=True)

In [7]:
b

tensor(0., requires_grad=True)

In [8]:
z=w*x+b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [9]:
y_pred=torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [11]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [12]:
loss= binary_cross_entropy_loss(y_pred,y)

In [13]:
loss.backward()

In [14]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


## Vector input Tensor 

In [20]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [21]:
y=(x**2).mean()

In [22]:
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [23]:
y.backward()

In [25]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [62]:
#clearing gradients
x=torch.tensor([2.0],requires_grad=True)

In [63]:
y=x**2
y

tensor([4.], grad_fn=<PowBackward0>)

In [64]:
y.backward()


In [65]:
x.grad

tensor([4.])

In [66]:
x.grad.zero_()

tensor([0.])

In [67]:
#disable gradient tracking

In [68]:
#option 1
x.requires_grad_(False)

tensor([2.])

In [69]:
#option2 detach()
 #we create completely new tensor that does not require gradients
z=x.detach()
z

tensor([2.])

In [71]:
#option3
with torch.no_grad():
    y=x**2
    y