In [2]:
import torch
print(torch.__version__)


2.7.1+cu118


# Creating a tensor

In [3]:
#using empty
a=torch.empty(2,3)

In [4]:
torch.empty(5,5)

tensor([[1.7554e-10, 1.7754e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [5]:
a

tensor([[1.7468e-10, 1.7754e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [6]:
#check type
type(a)

torch.Tensor

In [7]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#using rand
torch.rand(2,3)

tensor([[0.2219, 0.0324, 0.0665],
        [0.3758, 0.8490, 0.0467]])

### While using rand function eachtime it gives a new value,to prevent that we seed from this every time we use random function we will get same output 

In [10]:
#use of seed
torch.manual_seed(50)
torch.rand(2,3)

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [11]:
#using tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
#other ways

#arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [14]:
#linspace
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [15]:
#using eye 
#identitiy matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
#using full
torch.full((3,3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])