In [3]:
import torch
print(torch.__version__)


2.7.1+cu118


# Creating a tensor

In [4]:
#using empty
a=torch.empty(2,3)

In [5]:
torch.empty(5,5)

tensor([[1.7483e-18, 7.5250e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [6]:
a

tensor([[1.7356e-18, 7.5250e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [7]:
#check type
type(a)

torch.Tensor

In [8]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
#using rand
torch.rand(2,3)

tensor([[0.5336, 0.1386, 0.7012],
        [0.0106, 0.5152, 0.6513]])

### While using rand function eachtime it gives a new value,to prevent that we seed from this every time we use random function we will get same output 

In [11]:
#use of seed
torch.manual_seed(50)
torch.rand(2,3)

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [12]:
#using tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
#other ways

#arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [14]:
#linspace
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [15]:
#using eye 
#identitiy matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
#using full
torch.full((3,3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

## Tensors Shape


In [17]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
torch.empty_like(x)

tensor([[2306968192880,             0,             0],
        [            0,             0,             0]])

In [19]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

### Datatypes

In [21]:
#find data type
x.dtype

torch.int64

In [22]:
#assign data type
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [23]:
torch.tensor([1.0,2.0,3.0],dtype=torch.float32)

tensor([1., 2., 3.])

In [24]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations

#### Scalar operation

In [25]:
x=torch.rand(2,2)

In [26]:
x

tensor([[0.4605, 0.4877],
        [0.5927, 0.9634]])

In [27]:
#addition
x+2 

tensor([[2.4605, 2.4877],
        [2.5927, 2.9634]])

In [28]:
#subtraction
x-2

tensor([[-1.5395, -1.5123],
        [-1.4073, -1.0366]])

In [29]:
#mutiplication
x*2

tensor([[0.9209, 0.9754],
        [1.1853, 1.9268]])

In [30]:
#division 
x/3

tensor([[0.1535, 0.1626],
        [0.1976, 0.3211]])

In [31]:
#int division
(x*100)//3

tensor([[15., 16.],
        [19., 32.]])

In [32]:
#mod
((x*100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [33]:
#power
x**2

tensor([[0.2120, 0.2378],
        [0.3513, 0.9281]])

In [34]:
c=torch.tensor([1,-2,3,-4])

In [35]:
#absoute value
torch.abs(c)

tensor([1, 2, 3, 4])

In [36]:
#negative
torch.negative(c)

tensor([-1,  2, -3,  4])

In [37]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [38]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [39]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [40]:
#floor
torch.floor(d)


tensor([1., 2., 3., 4.])

In [41]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3.Reduction operation 

In [42]:
e=torch.randint(size=(2,3),low=0,high=10)
e

tensor([[8, 7, 5],
        [0, 7, 0]])

In [43]:
#sum
torch.sum(e)

tensor(27)

In [44]:
#sum along columns
torch.sum(e,dim=0)

tensor([ 8, 14,  5])

In [45]:
#sum along rows
torch.sum(e,dim=1)

tensor([20,  7])

In [46]:
#mean
torch.mean(e)
#as we are using integer tensor, it will give us error as mean of integers is not an integer, so we need to change the data type to float

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [47]:
torch.mean(e,dtype=torch.float32)

tensor(4.5000)

In [51]:
#mean along col
torch.mean(e,dim=0,dtype=torch.float32)

tensor([4.0000, 7.0000, 2.5000])

In [52]:
#median
torch.median(e)


tensor(5)

In [53]:
#max and min
torch.min(e),torch.max(e)


(tensor(0), tensor(8))

In [54]:
#product
torch.prod(e)

tensor(0)

In [57]:
#standard deviation
torch.std(e.float())

tensor(3.6194)

In [58]:
#variance
torch.var(e.float())

tensor(13.1000)

In [59]:
#argmax
torch.argmax(e)

tensor(0)

In [61]:
#argmin
torch.argmin(e)

tensor(3)

### Matrix operations

In [68]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

print(f)
print(g)

tensor([[0, 1, 5],
        [9, 8, 4]])
tensor([[9, 4],
        [2, 8],
        [7, 0]])


In [69]:
#matrix multiplication
torch.matmul(f, g)

tensor([[ 37,   8],
        [125, 100]])

In [70]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])
#dot product
torch.dot(vector1, vector2)

tensor(11)

In [71]:
#transpose
torch.transpose(f,0,1)


tensor([[0, 9],
        [1, 8],
        [5, 4]])

In [72]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[6., 2., 2.],
        [1., 8., 3.],
        [1., 6., 4.]])

In [73]:
#determinant
torch.det(h)

tensor(78.)

In [74]:
#inverse
torch.inverse(h)

tensor([[ 0.1795,  0.0513, -0.1282],
        [-0.0128,  0.2821, -0.2051],
        [-0.0256, -0.4359,  0.5897]])

### Comparison operations

In [75]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)

In [76]:
i,j

(tensor([[1, 0, 0],
         [9, 9, 6]]),
 tensor([[2, 3, 8],
         [2, 3, 9]]))

In [77]:
#greater than
torch.gt(i,j)

tensor([[False, False, False],
        [ True,  True, False]])

In [78]:
#less than
torch.lt(i,j)

tensor([[ True,  True,  True],
        [False, False,  True]])

In [79]:
#equal to
i==j

tensor([[False, False, False],
        [False, False, False]])

In [80]:
#not equal to
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [81]:
#greater than equal to
torch.ge(i,j) 


tensor([[False, False, False],
        [ True,  True, False]])

In [82]:
#lees tha equal to  
torch.le(i,j)

tensor([[ True,  True,  True],
        [False, False,  True]])

### Special functions

In [89]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[9., 5., 6.],
        [5., 5., 1.]])

In [84]:
#log
torch.log(k)

tensor([[0.6931, 1.7918, 2.0794],
        [2.0794, 2.1972, 1.3863]])

In [85]:
#exp
torch.exp(k)

tensor([[7.3891e+00, 4.0343e+02, 2.9810e+03],
        [2.9810e+03, 8.1031e+03, 5.4598e+01]])

In [86]:
#sqrt
torch.sqrt(k)

tensor([[1.4142, 2.4495, 2.8284],
        [2.8284, 3.0000, 2.0000]])

In [87]:
#sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.9975, 0.9997],
        [0.9997, 0.9999, 0.9820]])

In [90]:
#softmax
torch.softmax(k,dim=0)

tensor([[0.9820, 0.5000, 0.9933],
        [0.0180, 0.5000, 0.0067]])

In [93]:
#relu
torch.relu(k)

tensor([[9., 5., 6.],
        [5., 5., 1.]])

## Inplace operation

In [94]:
#so what happens is that whenever we perform some operations it stores that in a new tensor, which occupies the space so to reduce that we store that in the previous tensor 

In [95]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.6065, 0.5926, 0.7300],
        [0.9768, 0.9680, 0.1494]])
tensor([[0.9826, 0.7921, 0.5842],
        [0.9628, 0.3192, 0.5750]])


In [96]:
m.add_(n)

tensor([[1.5891, 1.3846, 1.3141],
        [1.9396, 1.2873, 0.7244]])

In [97]:
m

tensor([[1.5891, 1.3846, 1.3141],
        [1.9396, 1.2873, 0.7244]])

### Copying a Tensor

In [98]:
a=torch.rand(2,3)
a

tensor([[0.1538, 0.2540, 0.9703],
        [0.5020, 0.3018, 0.8832]])

In [99]:
b=a

In [102]:
b
#method 1 (in this method while changing a the original the copied b will also change as they are pointing to the same memory location,that is not desirable)

tensor([[0.1538, 0.2540, 0.9703],
        [0.5020, 0.3018, 0.8832]])

In [103]:
b=a.clone()

In [104]:
a[0][0]=100

In [105]:
a

tensor([[100.0000,   0.2540,   0.9703],
        [  0.5020,   0.3018,   0.8832]])

In [106]:
b

tensor([[0.1538, 0.2540, 0.9703],
        [0.5020, 0.3018, 0.8832]])